package net.sf.sketchlet.plugins.tetris;

/**
 * This interface allows an object to listen for
 * ScoreEvent's which are generated by a TetrisGame
 * everytime its score value changes.
 * 
 * @author Scott Clee
 */
public interface ScoreListener
{
    /**
     * This method is invoked everytime a the score
     * changes in a TetrisGame.
     * 
     * @param event a ScoreEvent
     */
    public void scoreChange(ScoreEvent event);
}
